version: "3"
services:
 
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

  redis:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '${REDIS_PORT}:6379'
      volumes: 
        - cache-data:/data
      env_file:
        - .env
      networks:
          - docker-service

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local
  cache-data:
    driver: local