version: "3"
services:
 
  mysql:
    image: mysql:latest
    container_name: mysql-fakebaas
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local